[2023-09-11T02:05:46.596+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.second_task scheduled__2023-09-09T00:00:00+00:00 [queued]>
[2023-09-11T02:05:46.683+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.second_task scheduled__2023-09-09T00:00:00+00:00 [queued]>
[2023-09-11T02:05:46.690+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-11T02:05:46.861+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): second_task> on 2023-09-09 00:00:00+00:00
[2023-09-11T02:05:46.880+0000] {standard_task_runner.py:57} INFO - Started process 329 to run task
[2023-09-11T02:05:47.050+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'second_task', 'scheduled__2023-09-09T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpfma9p8bu']
[2023-09-11T02:05:47.523+0000] {standard_task_runner.py:85} INFO - Job 248: Subtask second_task
[2023-09-11T02:06:09.383+0000] {task_command.py:415} INFO - Running <TaskInstance: our_first_dag_v4.second_task scheduled__2023-09-09T00:00:00+00:00 [running]> on host 2e8147b3a465
[2023-09-11T02:06:30.136+0000] {local_task_job_runner.py:228} INFO - Task exited with return code -9
[2023-09-11T02:07:44.305+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
