[2023-09-11T02:05:27.528+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FIBA_dag.connect_check scheduled__2023-09-06T00:00:00+00:00 [queued]>
[2023-09-11T02:05:27.606+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FIBA_dag.connect_check scheduled__2023-09-06T00:00:00+00:00 [queued]>
[2023-09-11T02:05:27.612+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-11T02:05:27.656+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): connect_check> on 2023-09-06 00:00:00+00:00
[2023-09-11T02:05:27.695+0000] {standard_task_runner.py:57} INFO - Started process 314 to run task
[2023-09-11T02:05:27.743+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'FIBA_dag', 'connect_check', 'scheduled__2023-09-06T00:00:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/FIBA.py', '--cfg-path', '/tmp/tmp8hruo9hy']
[2023-09-11T02:05:27.826+0000] {standard_task_runner.py:85} INFO - Job 238: Subtask connect_check
[2023-09-11T02:05:28.134+0000] {task_command.py:415} INFO - Running <TaskInstance: FIBA_dag.connect_check scheduled__2023-09-06T00:00:00+00:00 [running]> on host 2e8147b3a465
[2023-09-11T02:05:30.174+0000] {local_task_job_runner.py:228} INFO - Task exited with return code -9
